### ISSUE TITLE
HIGH - change column definition does not change the filter

### ISSUE THREAD

**Issue by Fangmingdu** [ceolter/angular-grid#194] opened 2015-06-08 17:30 UTC
I have a usage scenario which needs to change all columns based on user selection.
But the filter option does not change after I changed the columns.

There is a plunker for this. Can you take a look?
http://plnkr.co/edit/8dOgMlhmaftahd27RnWK?p=preview

(the filters for the column "Make" are all the options. after click on button "change columns". the filters are still the same and do not change.)

Thanks!

**Comment by ceolter** [comment] 2015-06-08 20:58
thank you for raising. the problem is some short-sightedness on my side. the filters are identified by column id's, and the column id's are currently just indexes from left to right. so the second filter stays with the second column, even though the column has totally changed. i will fix this one soon, expect the fix in this weekends release.

**Comment by Fangmingdu** [comment] 2015-06-08 20:59
Thanks! That's great.

**Comment by ceolter** [comment] 2015-06-10 21:50
fixed in master. the column filters are now identified using the colDef.field attribute.

**Closed by ceolter** 2015-06-10 21:50 UTC
