### ISSUE TITLE
angularCompileRows + quickFilterText doesn´t work together

### ISSUE THREAD

**Issue by livioalves** [ceolter/angular-grid#361] opened 2015-08-04 19:54 UTC
When I set angularCompileRows: true, I cannot use quickFilterText because it is readonly.

**Comment by chiptus** [comment] 2015-08-05 03:59
What are you doing exactly? I use them both on a few of my grids

**Comment by ceolter** [comment] 2015-08-05 07:50
could not reproduce so closing. if you want to reopen, please provide how to reproduce, providing a fiddle would be very helpful. or if it's a question, please use the forum. thanks :)

**Closed by ceolter** 2015-08-05 07:50 UTC
