### ISSUE TITLE
[BUG] Headers in firefox are not shown

### ISSUE THREAD

**Issue by lukelalo** [ceolter/angular-grid#36] opened 2015-04-03 12:45 UTC
Hi!

I've been testing your grid with some browsers, and it seems that headers in Firefox are not being shown (probably a z-index issue of the layer).

![angulargrid firefox headers](https://cloud.githubusercontent.com/assets/4819263/6982281/f5b640e8-da0f-11e4-8f63-573acd3d33a2.PNG)

Regards
Pablo García

**Comment by ceolter** [comment] 2015-04-03 12:48
Windows or Mac?

On 3 April 2015 at 13:45, lukelalo <notifications@github.com> wrote:

> Hi!
>
> I've been testing your grid with some browsers, and it seems that headers
> in Firefox are not being showed (probably a z-index issue of the layer).
>
> [image: angulargrid firefox headers]
> <https://cloud.githubusercontent.com/assets/4819263/6982281/f5b640e8-da0f-11e4-8f63-573acd3d33a2.PNG>
>
> Regards
> Pablo García
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/36>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by lukelalo** [comment] 2015-04-03 12:54
Windows

**Comment by ceolter** [comment] 2015-04-26 09:06
i can't reproduce this. is this still an issue with the latest?

**Comment by lukelalo** [comment] 2015-04-26 10:25
It seems I was testing with an old version of firerfox (33). If you've tested with the latest one in windows and it's working, it's fine for me to close this issue

**Comment by ceolter** [comment] 2015-04-26 11:21
cool, closing. thanks @lukelalo

**Closed by ceolter** 2015-04-26 11:21 UTC
