### ISSUE TITLE
Custom filters are broken in 1.7

### ISSUE THREAD

**Issue by AndreyGoDev** [ceolter/angular-grid#191] opened 2015-06-06 10:58 UTC
http://www.angulargrid.com/angular-grid-filtering/example2.html

When filtering on "Athlete" column, Chrome is throwing

`TypeError: Cannot read property 'toString' of undefined
    at http://www.angulargrid.com/angular-grid-filtering/example2.js:58:27
    at Array.forEach (native)
    at PersonFilter.doesFilterPass (http://www.angulargrid.com/angular-grid-filtering/example2.js:57:45)
    at FilterManager.doesFilterPass (http://www.angulargrid.com/dist/angular-grid.js:732:35)
    at InMemoryRowController.doesRowPassFilter (http://www.angulargrid.com/dist/angular-grid.js:3553:33)
    at InMemoryRowController.filterItems (http://www.angulargrid.com/dist/angular-grid.js:3382:22)
    at InMemoryRowController.doFilter (http://www.angulargrid.com/dist/angular-grid.js:3358:32)
    at InMemoryRowController.updateModel (http://www.angulargrid.com/dist/angular-grid.js:3147:18)
    at Grid.updateModelAndRefresh (http://www.angulargrid.com/dist/angular-grid.js:1997:32)
    at Grid.onFilterChanged (http://www.angulargrid.com/dist/angular-grid.js:1902:10)`

**Comment by ceolter** [comment] 2015-06-06 12:03
not a bug in the grid, rather i didn't update the documentation with a breaking change. already raised and discussed here:
http://www.angulargrid.com/forum/showthread.php?tid=2240

i've updated the doc's, so will be included in the next release. thanks.

**Closed** 2015-06-06 12:02 UTC
