### ISSUE TITLE
No data message in grid

### ISSUE THREAD

**Issue by joshikeerti** [ceolter/angular-grid#444] opened 2015-09-18 19:16 UTC
If I have an API that does not return any results, I want to display a no record found or a similar message inside the grid. Is there any option to do that currently?

**Comment by ceolter** [comment] 2015-09-19 07:57
duplicate of this:
https://github.com/ceolter/angular-grid/issues/88

it's on my list of items to do.

**Closed by ceolter** 2015-09-19 07:57 UTC
