### ISSUE TITLE
Bug-report on valueGetter

### ISSUE THREAD

**Issue by jovana** [ceolter/angular-grid#357] opened 2015-08-03 21:24 UTC
I have checked this page: http://www.angulargrid.com/angular-grid-value-getters/index.php for the working sample of the valueGetter.

For some reason if you create an valid json string (checked by jsonlint.com) it does not accept this function on valueGetter. 

<img width="558" alt="schermafbeelding 2015-08-03 om 23 08 16" src="https://cloud.githubusercontent.com/assets/645456/9048016/38006f92-3a36-11e5-9f68-07e2791f7a8f.png">
(console.log error's)

```json
[
    {
        "headerName": "Nr.",
        "field": "kl_id",
        "width": 100,
        "suppressMenu": true
    },
    {
        "headerName": "Naam",
        "field": "kl_naam"
    },
    {
        "headerName": "Status",
        "field": "kls_status",
        "valueGetter": "getTextItem"
    },
    {
        "headerName": "Saldo",
        "field": "totaal",
        "filter": "number"
    },
    {
        "headerName": "Leverancier",
        "field": "parent_naam"
    }
]
```

If I put an invalid json direct in the angularjs controller like below, it IS working. Now I will parse this json form serverside so I can not parse invalid json object.

```json
[
    {
        "headerName": "Nr.",
        "field": "kl_id",
        "width": 100,
        "suppressMenu": true
    },
    {
        "headerName": "Naam",
        "field": "kl_naam"
    },
    {
        "headerName": "Status",
        "field": "kls_status",
        "valueGetter": getTextItem  <<<--- this is the problem
    },
    {
        "headerName": "Saldo",
        "field": "totaal",
        "filter": "number"
    },
    {
        "headerName": "Leverancier",
        "field": "parent_naam"
    }
]
```

Please let me know if you need more info on this?

Many thanks for the create work!

**Comment by ceolter** [comment] 2015-08-04 09:35
this is not a bug (hence closing the issue, questions should be on the board!!).

the valueGetter should be an expression. so passing in the string 'getTextItem' would be the same as this:
``
valueGetter = functio() {
   return getTextItem;
}
```

which is not valid javascript

**Closed by ceolter** 2015-08-04 09:35 UTC

**Comment by jovana** [comment] 2015-08-04 16:39
I'am sorry! Thanks anyway for the response.

**Comment by ceolter** [comment] 2015-08-04 18:06
no worries!!! just tying to maintain order.
