### ISSUE TITLE
Sorting groups on group column doesn't work

### ISSUE THREAD

**Issue by ocombe** [ceolter/angular-grid#348] opened 2015-07-29 08:50 UTC
Hey, I've been working on the example for the groupSuppressRow and noticed that when I click on the group column (ie: country) the sort is all weird.
The first click on the column changes the order from:
- united states
- russia
- australia
- canada

to:
- mongolia
- united states
- australia
- canada

and clicking again (sorting in the other side) keeps the sort the same. Clicking one last times reverts to the original "no sort".

I'm not sure what happens here, but there's something wrong with group column. Sorting on any "non group" column works fine (even when grouped).

**Comment by ceolter** [comment] 2015-07-29 10:57
duplicate of
https://github.com/ceolter/angular-grid/issues/125

**Closed by ceolter** 2015-07-29 10:57 UTC

**Comment by ocombe** [comment] 2015-07-29 11:53
Woops my bad sorry :)
