### ISSUE TITLE
IE 8 support

### ISSUE THREAD

**Issue by gauravjhs** [ceolter/angular-grid#40] opened 2015-04-04 13:01 UTC
What all browser versions are supported?

**Comment by ceolter** [comment] 2015-04-04 13:23
'All modern browsers' is the goal, and then IE 9+.

I haven't tested with IE8, so don't know how it looks there.

**Comment by ceolter** [comment] 2015-04-04 13:29
You tried in IE8? Let me know if it works, or how badly it breaks!!!

**Comment by gauravjhs** [comment] 2015-04-06 05:35
It's not working as of now. 
Couple of things which i noticed

1. Array forEach loop do not work in IE 8.
2. addEventListener do not work in IE 8.

**Comment by TilmannBach** [comment] 2015-04-16 08:41
i can confirm gauravjhs experiences with forEach loop and addEventListener in IE8
after adding the forEach into IE8 (http://stackoverflow.com/a/22598415/1409864)
there are more complications:
* document.createElementNS 
  + IE8 doesnt support SVG?
* rowsToRemove.forEach(function (indexToRemove) { that.removeVirtualRow(indexToRemove); }); 
  + (rowsToRemove is undefined)

... i havent got it to run

**Comment by ceolter** [comment] 2015-04-16 08:43
No SVG in IE8 really?? Wow. Maybe just text characters then, ie + and - for
expand & contract etc.

**Comment by anandsumeet** [comment] 2015-05-05 07:03
Any plans to include IE8 support?  
If I am not wrong the site a few weeks back had a mention about support for IE8+ but now its not there.  
Please suggest what polyfill/shim to use to make it work.

**Comment by ceolter** [comment] 2015-05-06 16:45
I will remove the 'for ins' and have SVG optional. Will see how far that gets us. But I will be depending on the community to help with IE8. Its not something I will be championing myself.

**Comment by anandsumeet** [comment] 2015-05-07 04:37
The SVG problem can be resolved by providing gridOptions.icon object with markup for your own icons.  We used <span> tags with Font Awesome classes.
We are working on to identify all issues (at least for features we are using), and are almost done.  Will post the changes on this thread once done.  It will require a few polyfills to be added and a few lines of code to be adjusted.  Will revert on this soon.

**Comment by anandsumeet** [comment] 2015-05-07 04:44
The other issues are with bind method, forEach, addeventListener,  getBoundingRect, event object.  Adding polyfills for these from MDN can resolve most
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects
- for bounding rect we need to add height and width properties using the top & bottom, left & right properties respectively as the same are not supported in IE8
- for event, we need to add downEvent=downEvent||window.event

more later

**Comment by ceolter** [comment] 2015-05-07 06:11
A doc page on IE8 might be useful.

**Comment by anandsumeet** [comment] 2015-05-07 11:41
here in wiki or on your site?  I shall document all changes required and send across.  You may put it in docs/readme/wiki or add the modifications to master, I can do it with a pull request also.  Let me know how you wish to go about it.

**Comment by amcdnl** [comment] 2015-05-07 14:41
@ceolter Close this, you should only support evergreen browsers. ( latest - 1 )

**Comment by sudhakar** [comment] 2015-05-08 12:46
@amcdnl Very much with you on this. IMHO, supporting IE8 & below would require considerable development effort. Even Angular 1.3 has dropped support for IE8 https://code.angularjs.org/1.3.15/docs/guide/ie

**Comment by anandsumeet** [comment] 2015-05-09 04:37
I agree, but IE 8 becomes a necessary evil when catering to enterprises which are still stuck and haven't updated(there is a large majority).  Even MS is not supporting it anymore :)  
We have managed to make it work for now, so If author(s) wish to just keep a doc page/section with the required adjustments (there aren't many), I'll be happy to send in the details.

Hopefully IE 8/9 will die soon too!

**Comment by ceolter** [comment] 2015-05-11 18:50
please send on the details on how you got it working! (post here or email to info@angulargrid.com) as i mentioned in another post (or was it this one??) I won't be personally championing IE8 support, but if you have done the work and it's working, then we should at least document and share what you did!

**Comment by anandsumeet** [comment] 2015-05-14 05:15
This will make angulargrid work fine in IE8

* Use angularJS 1.2.28 (basically have to be <1.3, as IE8 support is dropped 1.3 onwards), can use lte IE8 comment in html>head

* add the following polyfills for addeventlistner, function.bind and array.forEach
 - https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Compatibility
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Polyfill

* IE8 doesnt support placeholder, so you may use http://jamesallardice.github.io/Placeholders.js/ or just avoid as it will only show text "null" in filter menu

* To avoid SVG issues, use markup with font awesome icons(or your own css), define the gridOptions.icons = {
 menu: '< i class="fa fa-bars"></i>',
 filter: '< i class="fa fa-filter"></i>',
 sortAscending: '< i class="fa fa-sort-asc"></i>',
 sortDescending: '< i class="fa fa-sort-desc"></i>',
 groupExpanded: '< i class="fa fa-plus-square"></i>',
 groupContracted: '< i class="fa fa-minus-square"></i>',
 columnGroupOpened: '< i class="fa fa-chevron-circle-down"></i>',
 columnGroupClosed: '< i class="fa fa-chevron-circle-right"></i>'
}

* File : Angular-Grid.js , Version : 1.4.1, modify the following lines
 - Line 551 : var y = sourceRect.top - parentRect.top + (sourceRect.bottom-sourceRect.top);  (because IE8 doesnt return height and width for bounding rects)
 - Line 2220 : downEvent = downEvent || window.event;
 - Line 2226 : moveEvent = moveEvent || window.event;

**Comment by ceolter** [comment] 2015-05-14 08:32
thanks @anandsumeet  , i'll put this into the online docs

**Comment by ceolter** [comment] 2015-07-01 13:29
it was always on my plan to publish the above, after i got rid of the 'forEach' calls, so many things to get done.

however, i plan on moving to TypeScript soon. does anyone know on this thread the implications of typescript generated javascript in IE8? i had a quick google and didn't find anything, but though i'd ask here, see if anyone here is more knowledgeable about it???

**Comment by ceolter** [comment] 2015-09-19 16:28
i'm going to close this issue. given the resource i have on the project (ie just me) i don't have the time to spend keeping support for IE8. sorry to those who required this :(

**Closed by ceolter** 2015-09-19 16:28 UTC
